### ISSUE TITLE
Add PHI to permissions

### ISSUE THREAD

**Issue by graft** [mountetna/janus#8]
We need to be able to flag user access to projects as either "phi-enabled" or "phi-censored", a Boolean column 'phi' probably suffices. This information should be presented in Janus permissions requests for a project.

**Comment by graft** [comment]
In #9 I add a 'restricted' column which implements this. Projects can give a user 'restricted' permission; this shows up in the permissions hash by upper-casing or lower-casing their permissions field (e.g., { perm: 'V:labors' } vs. { perm: 'v:labors' }), and is parsed correspondingly by Etna::User, which also has a can_see_restricted? method that checks this permission.

**Comment by jasondcater** [comment]
@graft I need to implement this for magma. Would you like me to take this?

**Comment by graft** [comment]
See above comment, this is mostly implemented. The only piece remaining it seems is:

1) Add a migration to add a 'restricted' column to the permissions model.
2) Update the method User#jwt_hash, which creates the header encoded in the token.

Etna::Auth already has the behavior to check the restricted permissions using Etna::User (in mountetna/etna#graft-route-names), see the specs there for the behavior. I could add this pretty easily as part of the graft-use-jwt branch, or you can do it separately, but in any case the Etna JWT stuff should be closed first.

**Comment by graft** [comment]
This is now implemented in #7, i added migrations in ae36681114dc37e86c6ea01c1b425cce79718aa1.

**Comment by jasondcater** [comment]
This is implemented using the 'privileged' column on the permissions table.
