### ISSUE TITLE
Use JWT for authentication

### ISSUE THREAD

**Issue by graft** [mountetna/janus#9]
If we have a signed token we can perhaps avoid the use of a database and a request cycle to get permissions for a user.

In a typical scenario, the user is browsing or interacting with a particular project and wishes to be authenticated to do that work. Currently the cycle looks like this:

1) User authenticates directly with Janus. Janus sets a cookie with a JANUS_TOKEN, a random string. It keeps a copy of the token in its token table.

2) The user makes a request to an application (say, Timur).

3) Timur asks Janus for information about the user and a specific project. Janus responds with user info and all permissions. Timur caches this response locally.

4) Timur uses its cached user + permissions info to grant the user access to functionality.

On subsequent requests, the user may start at (2) with their JANUS_TOKEN, and Timur may skip (3) using its cache.

This has a few features:
1) The caching means that Timur will authorize a token until its cache is expired, even if Janus wants to invalidate it.

2) Without caching, Timur must ask Janus for information on every request, to avoid becoming out-of-date.

3) Janus has no way to invalidate Timur's cache.

Given this fact, we can provide identical results using a JWT:

1) The user asks to authenticate with Janus, optionally specifying a project. Janus responds with user info, token expiry time and permissions for the indicated project (or perhaps all projects, or perhaps up to 5 projects).

2) Janus signs the above message using its private key.

Now everyone who sees this token (and also knows Janus's public key) knows two things:

1) The user's info, permissions, etc.

2) Janus has verified this information.

This should be good enough for Timur, etc., to get by.

However, project permissions might be too extensive to include in the token - for example, a user who belongs to hundreds of projects would not be able to include all of this information in their token.

Let's say I generate a token with approval for one project (or several projects), but want to use Timur with yet another project. I.e., my token authorizes me for project 'bogwart', but I want to view project 'nixie'. Timur knows I am an authorized Janus user but has no idea whether I am allowed to see project 'nixie'. What does it do?

1) It can send the user to Janus to re-issue a token, overwriting the existing token. This might produce some sort of dueling-banjos scenario if I am switching tabs between two projects, where I am constantly being forced to get a new Janus token. Since this involves a redirect to Janus, it seems like a bad idea.

2) It can ask Janus for additional permissions and cache them locally. This means Timur (et al) have to look in two places for permissions, first the token and then a permissions table. Seems klunky and doesn't avoid having a database, which was the entire point.

3) It can ask Janus for additional permissions and set them in its own signed cookie. This additional permissions cookie is a way for Timur to cache stuff on the client side without having to worry about a database.

More later.

**Comment by graft** [comment]
Implemented using OpenSSL's PKey methods.

**Comment by jasondcater** [comment]
This  was implemented in the `graft-use-jwt` branch. The branch was merged into master.
